# Generated by Django 6.0.2 on 2026-02-19 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('capacite_max', models.PositiveIntegerField()),
                ('heure_verrouillage', models.TimeField(blank=True, null=True)),
                ('heure_deverrouillage', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffectationSalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_tiers_temps', models.BooleanField(default=False)),
                ('capacite_reservee', models.PositiveIntegerField(blank=True, null=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_salles', to='exams.examen')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='rooms.salle')),
            ],
            options={
                'unique_together': {('examen', 'salle')},
            },
        ),
    ]
