# Generated by Codex on 2026-03-31

from django.db import migrations, models


def forwards(apps, schema_editor):
    Examen = apps.get_model("exams", "Examen")
    AffectationSalle = apps.get_model("rooms", "AffectationSalle")

    for exam in Examen.objects.all():
        affectations = list(AffectationSalle.objects.filter(examen_id=exam.pk).order_by("pk"))
        if not affectations:
            continue

        room_count = len(affectations)
        required = max(0, exam.nb_surveillants_requis or 0)
        base = required // room_count
        remainder = required % room_count

        for index, affectation in enumerate(affectations):
            affectation.temps_majore = affectation.is_tiers_temps
            affectation.nb_surveillants_requis = base + (1 if index < remainder else 0)
            affectation.save(update_fields=["temps_majore", "nb_surveillants_requis"])


def backwards(apps, schema_editor):
    AffectationSalle = apps.get_model("rooms", "AffectationSalle")

    for affectation in AffectationSalle.objects.all():
        affectation.is_tiers_temps = affectation.temps_majore
        affectation.capacite_reservee = None
        affectation.save(update_fields=["is_tiers_temps", "capacite_reservee"])


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_examen_add_ue"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salle",
            old_name="heure_deverrouillage",
            new_name="heure_debut_verrouillage",
        ),
        migrations.RenameField(
            model_name="salle",
            old_name="heure_verrouillage",
            new_name="heure_fin_verrouillage",
        ),
        migrations.AddField(
            model_name="affectationsalle",
            name="temps_majore",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="affectationsalle",
            name="nb_surveillants_requis",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="salle",
            name="capacite_max",
        ),
        migrations.RemoveField(
            model_name="affectationsalle",
            name="is_tiers_temps",
        ),
        migrations.RemoveField(
            model_name="affectationsalle",
            name="capacite_reservee",
        ),
    ]
