# Generated by Django 6.0.2 on 2026-04-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_watchers_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='capacite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
