# Generated by Django 6.0.2 on 2026-02-19 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.anneeuniversitaire')),
            ],
            options={
                'ordering': ['-date_debut'],
                'unique_together': {('annee_universitaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('nb_eleves', models.PositiveIntegerField()),
                ('nb_eleves_tiers_temps', models.PositiveIntegerField(default=0)),
                ('nb_surveillants_requis', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('INITIE', 'Initié'), ('INCOMPLET', 'Incomplet'), ('COMPLET', 'Complet'), ('TERMINE', 'Terminé')], default='INITIE', max_length=12)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens_responsable', to=settings.AUTH_USER_MODEL)),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='academics.up')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='exams.sessionexamen')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
