# Generated by Codex on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_FORMATION_NAME = 'Formation par défaut'


def forwards(apps, schema_editor):
    AnneeUniversitaire = apps.get_model('academics', 'AnneeUniversitaire')
    Formation = apps.get_model('academics', 'Formation')
    UE = apps.get_model('academics', 'UE')
    SessionExamen = apps.get_model('exams', 'SessionExamen')

    ue_ids = list(UE.objects.values_list('pk', flat=True))
    formations_by_year = {}

    for year in AnneeUniversitaire.objects.all():
        formation, _ = Formation.objects.get_or_create(
            annee_universitaire_id=year.pk,
            nom=DEFAULT_FORMATION_NAME,
        )
        if ue_ids:
            formation.ues.add(*ue_ids)
        formations_by_year[year.pk] = formation.pk

    for session in SessionExamen.objects.all():
        session.formation_id = formations_by_year.get(session.annee_universitaire_id)
        session.save(update_fields=['formation'])


def backwards(apps, schema_editor):
    SessionExamen = apps.get_model('exams', 'SessionExamen')

    for session in SessionExamen.objects.exclude(formation_id=None).select_related('formation', 'formation__annee_universitaire'):
        session.annee_universitaire_id = session.formation.annee_universitaire_id
        session.save(update_fields=['annee_universitaire'])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('academics', '0002_formation'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexamen',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.formation'),
        ),
        migrations.RunPython(forwards, backwards, atomic=True),
        migrations.AlterField(
            model_name='sessionexamen',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.formation'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexamen',
            unique_together={('formation', 'nom')},
        ),
        migrations.RemoveField(
            model_name='sessionexamen',
            name='annee_universitaire',
        ),
        migrations.AlterModelOptions(
            name='sessionexamen',
            options={'ordering': ['formation__nom', '-date_debut', 'nom']},
        ),
    ]
