# Generated by Codex on 2026-03-31

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Examen = apps.get_model("exams", "Examen")

    for exam in Examen.objects.select_related("up__ue"):
        exam.ue_id = exam.up.ue_id
        exam.save(update_fields=["ue"])


def backwards(apps, schema_editor):
    Examen = apps.get_model("exams", "Examen")
    UP = apps.get_model("academics", "UP")

    for exam in Examen.objects.exclude(ue_id=None):
        up = UP.objects.filter(ue_id=exam.ue_id).order_by("nom").first()
        if up is not None:
            exam.up_id = up.pk
            exam.save(update_fields=["up"])


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_create_default_sessions"),
        ("exams", "0002_sessionexamen_formation"),
    ]

    operations = [
        migrations.AddField(
            model_name="examen",
            name="ue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="examens",
                to="academics.ue",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="examen",
            name="ue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="examens",
                to="academics.ue",
            ),
        ),
    ]
