# Generated by Codex on 2026-03-31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_surveillance_by_room"),
        ("exams", "0003_examen_add_ue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examen",
            name="up",
        ),
        migrations.RemoveField(
            model_name="examen",
            name="responsable",
        ),
        migrations.RemoveField(
            model_name="examen",
            name="nb_eleves",
        ),
        migrations.RemoveField(
            model_name="examen",
            name="nb_eleves_tiers_temps",
        ),
        migrations.RemoveField(
            model_name="examen",
            name="nb_surveillants_requis",
        ),
    ]
