# Generated by Django 6.0.2 on 2026-04-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_legacy_exam_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionexamen',
            options={'ordering': ['formation__nom', 'nom']},
        ),
        migrations.RemoveField(
            model_name='sessionexamen',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='sessionexamen',
            name='date_fin',
        ),
    ]
