# Generated by Django 6.0.2 on 2026-05-05 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_rebalance_ue_colors_balanced_random'),
        ('exams', '0006_reset_exams_and_enforce_single_exam_per_ue_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenUPCoefficient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coefficient', models.PositiveIntegerField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_coefficients', to='exams.examen')),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_coefficients', to='academics.up')),
            ],
            options={
                'ordering': ['up__nom'],
                'unique_together': {('examen', 'up')},
            },
        ),
    ]
