# Generated by Django 6.0.2 on 2026-02-19 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillances', to='exams.examen')),
                ('surveillant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('examen', 'surveillant')},
            },
        ),
    ]
