# Generated by Codex on 2026-03-31

import django.db.models.deletion
from django.db import migrations, models


def _build_placeholder_room_name(exam, salle_model):
    base = f"Salle migrée - {exam.nom}"
    candidate = base[:255]
    index = 2
    while salle_model.objects.filter(nom=candidate).exists():
        suffix = f" {index}"
        candidate = f"{base[: max(1, 255 - len(suffix))]}{suffix}"
        index += 1
    return candidate


def forwards(apps, schema_editor):
    Surveillance = apps.get_model("assignments", "Surveillance")
    Salle = apps.get_model("rooms", "Salle")
    AffectationSalle = apps.get_model("rooms", "AffectationSalle")

    surveillances = (
        Surveillance.objects.select_related("examen")
        .order_by("examen_id", "created_at", "pk")
    )
    exam_ids = list(dict.fromkeys(surveillances.values_list("examen_id", flat=True)))

    for exam_id in exam_ids:
        exam_surveillances = list(surveillances.filter(examen_id=exam_id))
        affectations = list(AffectationSalle.objects.filter(examen_id=exam_id).order_by("pk"))

        if not affectations:
            exam = exam_surveillances[0].examen
            salle = Salle.objects.create(nom=_build_placeholder_room_name(exam, Salle))
            affectations = [
                AffectationSalle.objects.create(
                    examen_id=exam_id,
                    salle_id=salle.pk,
                    temps_majore=False,
                    nb_surveillants_requis=len(exam_surveillances),
                )
            ]

        loads = {affectation.pk: 0 for affectation in affectations}

        for surveillance in exam_surveillances:
            target = min(
                affectations,
                key=lambda affectation: (
                    loads[affectation.pk] >= affectation.nb_surveillants_requis,
                    loads[affectation.pk],
                    str(affectation.pk),
                ),
            )
            surveillance.affectation_salle_id = target.pk
            surveillance.save(update_fields=["affectation_salle"])
            loads[target.pk] += 1


def backwards(apps, schema_editor):
    Surveillance = apps.get_model("assignments", "Surveillance")

    for surveillance in Surveillance.objects.exclude(affectation_salle_id=None).select_related("affectation_salle__examen"):
        surveillance.examen_id = surveillance.affectation_salle.examen_id
        surveillance.save(update_fields=["examen"])


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_examen_add_ue"),
        ("rooms", "0002_room_watchers_restructure"),
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveillance",
            name="affectation_salle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveillances",
                to="rooms.affectationsalle",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="surveillance",
            name="affectation_salle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveillances",
                to="rooms.affectationsalle",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveillance",
            unique_together={("affectation_salle", "surveillant")},
        ),
        migrations.RemoveField(
            model_name="surveillance",
            name="examen",
        ),
    ]
