# Generated by Django 6.0.2 on 2026-04-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_surveillance_by_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillance',
            name='is_responsable_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveillance',
            name='is_responsable_salle',
            field=models.BooleanField(default=False),
        ),
    ]
