# Generated by Django 6.0.2 on 2026-02-19 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeUniversitaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('responsables', models.ManyToManyField(blank=True, related_name='ues_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('matiere', models.CharField(blank=True, max_length=255)),
                ('responsables', models.ManyToManyField(blank=True, related_name='ups_responsable', to=settings.AUTH_USER_MODEL)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ups', to='academics.ue')),
            ],
            options={
                'unique_together': {('ue', 'nom')},
            },
        ),
    ]
