# Generated by Codex on 2026-03-25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='academics.anneeuniversitaire')),
                ('ues', models.ManyToManyField(blank=True, related_name='formations', to='academics.ue')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('annee_universitaire', 'nom')},
            },
        ),
    ]
