# Generated by Codex on 2026-03-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_formation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ue',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='up',
            options={'ordering': ['ue__nom', 'nom']},
        ),
    ]
