# Generated by Django 6.0.2 on 2026-04-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_reassign_ue_colors'),
        ('exams', '0005_alter_sessionexamen_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UP',
        ),
    ]
