# Generated by Django 6.0.2 on 2026-04-03 15:45

from django.db import migrations, models


def populate_code_ue(apps, schema_editor):
    UE = apps.get_model("academics", "UE")
    used_codes = set()

    for ue in UE.objects.all().order_by("nom", "pk"):
        if ue.code_ue:
            normalized = ue.code_ue.strip().upper().replace(" ", "")
            ue.code_ue = normalized
            used_codes.add(normalized)
            ue.save(update_fields=["code_ue"])
            continue

        index = 1
        while True:
            candidate = f"UE{index:03d}"
            if candidate not in used_codes:
                ue.code_ue = candidate
                ue.save(update_fields=["code_ue"])
                used_codes.add(candidate)
                break
            index += 1


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_delete_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='code_ue',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(populate_code_ue, noop),
    ]
