# Generated by Django 6.0.2 on 2026-04-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_reintroduce_up_and_scope_ue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ue',
            name='responsables',
        ),
    ]
